language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install pep8
script:
  - pep8 --max-line-length=120 resttools
  - nosetests --with-coverage --cover-package=resttools
after_script:
  - coverage report
before_deploy:
  - git describe --tags > resttools/VERSION
deploy:
  provider: script
  skip_cleanup: true
  script: pip install twine && python setup.py sdist && twine upload dist/*
  on:
    tags: true
    python: '3.6'
