language: python
python:
  - '2.7'
  - '3.6'
install:
  - pip install -r requirements.txt
  - set | grep TRAVIS
  - set | grep GIT
before_script:
  - pip install coverage
  - pip install pep8
script:
  - pep8 --max-line-length=120 resttools
  - nosetests --with-coverage --cover-package=resttools
after_script:
  - coverage report
before_deploy:
  - git describe --tags > resttools/VERSION
deploy:
  provider: pypi
  user: jeffrouw
  password:
    secure: Hk16fdmiYvODsFjQl6hVF8LwphRUzIXOO7KA8bD3m2xM6hw9a01Tf0sv37wSUEJSJOURv1K8MBSOdE7yFGaYB5it7DvGI3ozGX2RMcCdkKWD6wtRHxTy1r8iOpQXEaOkYo32ZbVYQGAjVoJHlIf5U/IkyJAV2khJwiWd66PTX/8=
  on:
    tags: true
    python: '3.6'
