language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install pep8
script:
#  - pep8 --max-line-length=120
  - nosetests --with-coverage --cover-package=resttools 
after_script:
  - coverage report

