<gws class="gws" version="2">
   


<group class="group" version="2">

 <xsrf class="xsrf"></xsrf>
 <regid class="regid">unittestcba3f54f759e6c9432004381</regid>
 <name class="name">u_fox_unittest</name>
 <title class="title">Test group for resttools unittest</title>
 <description class="description">This is a mock test group for resttools unit testing</description>
 <createtime class="createtime">1206721704000</createtime>
 <modifytime class="modifytime">1384984147140</modifytime>
 <membermodifytime class="membermodifytime">1424985698647</membermodifytime>

 <contact class="contact">fox</contact>

 <authnfactor class="authnfactor">1</authnfactor>
 <classification class="classification">r</classification>
 <dependson class="dependson">u_cac_all</dependson>
 <gid class="gid">65942</gid>

  
    <affiliates class="affiliates">
              <affiliate class="affiliate" name="google"
             status="inactive"              sender="none"             />
         <affiliate class="affiliate" name="radius"
             status="active"                         />
         <affiliate class="affiliate" name="netid"
             status="inactive"        forward=""                   />
      </affiliates>
 

 <emailenabled class="emailenabled">disabled</emailenabled>
   <publishemail class="publishemail">u_fox_unittest@exchange.washington.edu</publishemail>
     <reporttoowner class="reporttoowner">no</reporttoowner>
   
  <authorigs class="authorigs">
         <authorig class="authorig" type="none">dc=none</authorig>
     </authorigs>

  

    


 
  <admins class="admins">
          <admin class="admin" type="uwnetid" name="Jim Fox">fox</admin>
       </admins>
  <updaters class="updaters">
          <updater class="updater" type="dns" name="Fox's office desktop">x315.cac.washington.edu</updater>
       </updaters>
  <creators class="creators">
          <creator class="creator" type="dns" name="Fox's office desktop">x315.cac.washington.edu</creator>
             <creator class="creator" type="dns" name="tegrity.uw.edu">tegrity.uw.edu</creator>
       </creators>
  <readers class="readers">
          <reader class="reader" type="group" name="spud test with [&amp;#21494~] unicode?">u_fox_00-spud99</reader>
             <reader class="reader" type="none" name="EveryEntity">dc=all</reader>
       </readers>
  <optins class="optins">
          <optin class="optin" type="none" name="EveryEntity">dc=all</optin>
       </optins>
  <optouts class="optouts">
          <optout class="optout" type="none" name="EveryEntity">dc=all</optout>
       </optouts>

</group>

</gws>

